version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: final_project_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: final_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
