spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/final_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    cors:
      enabled: true
      mappings:
        "[/api/**]":
          allowed-origins: ${ALLOWED_ORIGINS:https://chartchai-class.github.io,https://43-142-75-247.sslip.io}
          allowed-methods: "*"
          allowed-headers: "*"
          max-age: 3600

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:change-me-secret}
    expiration: ${JWT_EXP_SECONDS:86400}

storage:
  provider: ${STORAGE_PROVIDER:local} # local | s3
  s3:
    endpoint: ${S3_ENDPOINT:https://kpyoonwsfzkdddpvkaoo.storage.supabase.co/storage/v1/s3}
    region: ${S3_REGION:ap-southeast-2}
    bucket: ${S3_BUCKET:social-anti-fake-news}
    accessKey: ${S3_ACCESS_KEY:}
    secretKey: ${S3_SECRET_KEY:}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
